version: '3'
services:
  extensions-postgres-test:
    image: camptocamp/postgres:9.6
    container_name: 'extensions-postgres-test'
    ports:
      - 65432:5432
    environment:
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_USER=extensions
      - POSTGRES_DB=extensions